# Generated by Django 4.0.3 on 2022-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0004_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(),
        ),
    ]
