# Generated by Django 4.0.3 on 2022-03-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0005_alter_rent_end_date_alter_rent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.location'),
        ),
    ]
