# Generated by Django 4.0.3 on 2022-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0006_alter_rent_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('car', 'start_date', 'end_date')},
        ),
    ]
